//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray;

__attribute__((visibility("hidden")))
@interface CFobLicVerifier : NSObject
{
    struct OpaqueSecKeyRef *_publicKey;
    NSArray *_blacklist;
}

+ (id)completePublicKeyPEM:(id)arg1;
@property(retain) struct OpaqueSecKeyRef *publicKey; // @synthesize publicKey=_publicKey;
@property(copy, nonatomic) NSArray *blacklist; // @synthesize blacklist=_blacklist;
- (void).cxx_destruct;
- (BOOL)verifyRegCode:(id)arg1 forName:(id)arg2 error:(id *)arg3;
- (BOOL)setPublicKey:(id)arg1 error:(id *)arg2;

@end

