//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSRunningApplication.h>

@interface NSRunningApplication (SMSandbox)
+ (struct __SecRequirement *)serverRequirement;
+ (struct __SecRequirement *)clientRequirement;
+ (struct __SecRequirement *)sandboxRequirement;
@property(readonly, nonatomic) BOOL hasServerEntitlement;
@property(readonly, nonatomic) BOOL hasClientEntitlement;
@property(readonly, nonatomic) BOOL hasSandbox;
- (BOOL)validWithRequirement:(struct __SecRequirement *)arg1 withCacheKey:(void *)arg2;
@end

