//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSWindowController.h>

@class NSImageView, NSTextView, SMAcknowledgmentsWindowController, SMView;

__attribute__((visibility("hidden")))
@interface SMAboutWindowController : NSWindowController
{
    NSImageView *_imageView;
    NSTextView *_textView;
    SMView *_backgroundView;
    SMAcknowledgmentsWindowController *_acknowledgmentsWindowController;
}

@property(retain, nonatomic) SMAcknowledgmentsWindowController *acknowledgmentsWindowController; // @synthesize acknowledgmentsWindowController=_acknowledgmentsWindowController;
@property(nonatomic) __weak SMView *backgroundView; // @synthesize backgroundView=_backgroundView;
@property(nonatomic) NSTextView *textView; // @synthesize textView=_textView;
@property(nonatomic) __weak NSImageView *imageView; // @synthesize imageView=_imageView;
- (void).cxx_destruct;
- (void)showAcknowledgments:(id)arg1;
- (void)hideAboutWindow:(id)arg1;
- (void)showAboutWindow:(id)arg1;
- (void)close:(id)arg1;
- (void)toggleAboutWindow:(id)arg1;
- (void)cancelOperation:(id)arg1;
- (void)windowDidLoad;
- (id)windowNibName;

@end

