//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSWindowController.h>

@class NSTextView;

__attribute__((visibility("hidden")))
@interface SMAcknowledgmentsWindowController : NSWindowController
{
    NSTextView *_textView;
}

@property NSTextView *textView; // @synthesize textView=_textView;
- (void)close:(id)arg1;
- (void)cancelOperation:(id)arg1;
- (void)windowDidLoad;
- (id)windowNibName;

@end

