//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSApplicationDelegate-Protocol.h"
#import "SMLicenseWindowControllerDelegate-Protocol.h"
#import "SUUpdaterDelegate-Protocol.h"

@class NSString, SMAboutWindowController, SMLicenseWindowController, SMMainWindowController, SUUpdater;

__attribute__((visibility("hidden")))
@interface SMAppDelegate : NSObject <SMLicenseWindowControllerDelegate, SUUpdaterDelegate, NSApplicationDelegate>
{
    BOOL _finishedLaunch;
    BOOL _firstLaunch;
    BOOL _registeredOrTrial;
    SUUpdater *_updater;
    SMMainWindowController *_mainWindowController;
    SMAboutWindowController *_aboutWindowController;
    SMLicenseWindowController *_licenseWindowController;
}

+ (void)restoreWindowWithIdentifier:(id)arg1 state:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;
@property(nonatomic) BOOL registeredOrTrial; // @synthesize registeredOrTrial=_registeredOrTrial;
@property(nonatomic) BOOL firstLaunch; // @synthesize firstLaunch=_firstLaunch;
@property(nonatomic) BOOL finishedLaunch; // @synthesize finishedLaunch=_finishedLaunch;
@property(retain, nonatomic) SMLicenseWindowController *licenseWindowController; // @synthesize licenseWindowController=_licenseWindowController;
@property(retain, nonatomic) SMAboutWindowController *aboutWindowController; // @synthesize aboutWindowController=_aboutWindowController;
@property(retain, nonatomic) SMMainWindowController *mainWindowController; // @synthesize mainWindowController=_mainWindowController;
@property(retain, nonatomic) SUUpdater *updater; // @synthesize updater=_updater;
- (void).cxx_destruct;
- (void)updater:(id)arg1 didAbortWithError:(id)arg2;
- (void)licenseWindowControllerDidClose:(id)arg1;
- (void)licenseWindowControllerDidStartTrial:(id)arg1;
- (void)licenseWindowControllerDidRegister:(id)arg1;
- (void)injectAndSelect:(id)arg1 userData:(id)arg2 error:(id *)arg3;
- (void)inject:(id)arg1 userData:(id)arg2 error:(id *)arg3;
- (id)createLicenseWindowController;
- (id)createAboutWindowController;
- (id)createMainWindowController;
- (BOOL)connectToApplication:(id)arg1 selectionMode:(BOOL)arg2;
- (BOOL)validateUserInterfaceItem:(id)arg1;
- (void)visitTwitter:(id)arg1;
- (void)visitWebsite:(id)arg1;
- (void)sendGeneralQuestion:(id)arg1;
- (void)showLicense:(id)arg1;
- (void)showAbout:(id)arg1;
- (void)showMainWindow:(id)arg1;
- (void)checkForUpdates:(id)arg1;
- (unsigned long long)applicationShouldTerminate:(id)arg1;
- (BOOL)applicationShouldHandleReopen:(id)arg1 hasVisibleWindows:(BOOL)arg2;
- (void)applicationDidFinishLaunching:(id)arg1;
- (void)applicationWillFinishLaunching:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

