//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSWindowController.h>

#import "NSTableViewDelegate-Protocol.h"
#import "NSTextFieldDelegate-Protocol.h"
#import "NSWindowDelegate-Protocol.h"

@class NSArrayController, NSButton, NSSearchField, NSString, NSTableView;
@protocol SMAttachWindowControllerDelegate;

__attribute__((visibility("hidden")))
@interface SMAttachWindowController : NSWindowController <NSWindowDelegate, NSTextFieldDelegate, NSTableViewDelegate>
{
    NSString *_selectedBundleIdentifier;
    id <SMAttachWindowControllerDelegate> _delegate;
    NSTableView *_tableView;
    NSSearchField *_searchField;
    NSButton *_allCheckbox;
    NSArrayController *_applicationsController;
}

@property(retain, nonatomic) NSArrayController *applicationsController; // @synthesize applicationsController=_applicationsController;
@property(nonatomic) __weak NSButton *allCheckbox; // @synthesize allCheckbox=_allCheckbox;
@property(nonatomic) __weak NSSearchField *searchField; // @synthesize searchField=_searchField;
@property(nonatomic) __weak NSTableView *tableView; // @synthesize tableView=_tableView;
@property(nonatomic) __weak id <SMAttachWindowControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(copy, nonatomic) NSString *selectedBundleIdentifier; // @synthesize selectedBundleIdentifier=_selectedBundleIdentifier;
- (void).cxx_destruct;
- (void)controlTextDidChange:(id)arg1;
- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forTableColumn:(id)arg3 row:(long long)arg4;
- (void)updateFilterPredicate;
- (void)doubleClickTableRow:(id)arg1;
- (void)attachApplication:(id)arg1;
- (void)cancel:(id)arg1;
- (void)toggleAllApplications:(id)arg1;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

