//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSData, NSXPCConnection;

__attribute__((visibility("hidden")))
@interface SMAuthorizedInjector : NSObject
{
    struct AuthorizationOpaqueRef *_authRef;
    NSXPCConnection *_installerConnection;
    NSXPCConnection *_injectorConnection;
    NSXPCConnection *_injector32Connection;
    NSData *_authorization;
}

@property(copy, nonatomic) NSData *authorization; // @synthesize authorization=_authorization;
@property(retain, nonatomic) NSXPCConnection *injector32Connection; // @synthesize injector32Connection=_injector32Connection;
@property(retain, nonatomic) NSXPCConnection *injectorConnection; // @synthesize injectorConnection=_injectorConnection;
@property(retain, nonatomic) NSXPCConnection *installerConnection; // @synthesize installerConnection=_installerConnection;
- (void).cxx_destruct;
- (void)injectFrameworkAtURL:(id)arg1 intoApplicationWithPID:(int)arg2 architecture:(unsigned long long)arg3 completion:(CDUnknownBlockType)arg4;
- (void)injectFrameworkWithToolAtURL:(id)arg1 withMachInjectFrameworkAtURL:(id)arg2 into32BitApplicationWithPID:(int)arg3 completion:(CDUnknownBlockType)arg4;
- (void)injectFrameworkWithToolAtURL:(id)arg1 withMachInjectFrameworkAtURL:(id)arg2 intoApplicationWithPID:(int)arg3 completion:(CDUnknownBlockType)arg4;
- (void)installToolsWithCompletion:(CDUnknownBlockType)arg1;
- (id)init;

@end

