//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <SMFoundation/SMView.h>

@class NSNumber;

__attribute__((visibility("hidden")))
@interface SMAutoresizingSelectionView : SMView
{
    BOOL _enabled;
    NSNumber *_flexibleMarginLeft;
    NSNumber *_flexibleMarginRight;
    NSNumber *_flexibleMarginBottom;
    NSNumber *_flexibleMarginTop;
    NSNumber *_flexibleWidth;
    NSNumber *_flexibleHeight;
}

@property(nonatomic, getter=isEnabled) BOOL enabled; // @synthesize enabled=_enabled;
@property(retain, nonatomic) NSNumber *flexibleHeight; // @synthesize flexibleHeight=_flexibleHeight;
@property(retain, nonatomic) NSNumber *flexibleWidth; // @synthesize flexibleWidth=_flexibleWidth;
@property(retain, nonatomic) NSNumber *flexibleMarginTop; // @synthesize flexibleMarginTop=_flexibleMarginTop;
@property(retain, nonatomic) NSNumber *flexibleMarginBottom; // @synthesize flexibleMarginBottom=_flexibleMarginBottom;
@property(retain, nonatomic) NSNumber *flexibleMarginRight; // @synthesize flexibleMarginRight=_flexibleMarginRight;
@property(retain, nonatomic) NSNumber *flexibleMarginLeft; // @synthesize flexibleMarginLeft=_flexibleMarginLeft;
- (void).cxx_destruct;
- (struct CGSize)intrinsicContentSize;
- (void)drawImage:(id)arg1;
- (void)drawRect:(struct CGRect)arg1;
- (void)mouseDown:(id)arg1;
- (void)viewWillUninstall;
- (void)viewDidInstall;
- (id)initWithFrame:(struct CGRect)arg1;

@end

