//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <SMFoundation/SMViewController.h>

#import "NSOutlineViewDataSource-Protocol.h"
#import "NSOutlineViewDelegate-Protocol.h"
#import "NSTableViewDelegate-Protocol.h"
#import "NSTextFieldDelegate-Protocol.h"

@class NSArray, NSOutlineView, NSPredicate, NSSearchField, NSString, NSTextField, NSTreeController, SMDelayedInvocation, SMInterfaceServer, SMInterfaceTreeNode;
@protocol SMComponentOutlineControllerDelegate;

__attribute__((visibility("hidden")))
@interface SMComponentOutlineController : SMViewController <NSOutlineViewDataSource, NSOutlineViewDelegate, NSTableViewDelegate, NSTextFieldDelegate>
{
    BOOL _constraintsFilter;
    BOOL _cellsFilter;
    BOOL _layersFilter;
    BOOL _updatingSelectedTreeNodes;
    SMInterfaceServer *_selectedServer;
    id <SMComponentOutlineControllerDelegate> _delegate;
    NSOutlineView *_outlineView;
    NSSearchField *_searchField;
    NSTreeController *_treeNodesController;
    NSArray *_rootTreeNodes;
    SMInterfaceTreeNode *_focusTreeNode;
    NSString *_filterString;
    NSPredicate *_filterPredicate;
    NSArray *_expandedItems;
    NSTextField *_notConnectedLabel;
    SMDelayedInvocation *_fitColumnInvocation;
}

+ (id)keyPathsForValuesAffectingConnected;
@property(retain, nonatomic) SMDelayedInvocation *fitColumnInvocation; // @synthesize fitColumnInvocation=_fitColumnInvocation;
@property(nonatomic) BOOL updatingSelectedTreeNodes; // @synthesize updatingSelectedTreeNodes=_updatingSelectedTreeNodes;
@property(nonatomic) __weak NSTextField *notConnectedLabel; // @synthesize notConnectedLabel=_notConnectedLabel;
@property(copy, nonatomic) NSArray *expandedItems; // @synthesize expandedItems=_expandedItems;
@property(retain, nonatomic) NSPredicate *filterPredicate; // @synthesize filterPredicate=_filterPredicate;
@property(copy, nonatomic) NSString *filterString; // @synthesize filterString=_filterString;
@property(nonatomic) BOOL layersFilter; // @synthesize layersFilter=_layersFilter;
@property(nonatomic) BOOL cellsFilter; // @synthesize cellsFilter=_cellsFilter;
@property(nonatomic) BOOL constraintsFilter; // @synthesize constraintsFilter=_constraintsFilter;
@property(retain, nonatomic) SMInterfaceTreeNode *focusTreeNode; // @synthesize focusTreeNode=_focusTreeNode;
@property(copy, nonatomic) NSArray *rootTreeNodes; // @synthesize rootTreeNodes=_rootTreeNodes;
@property(retain, nonatomic) NSTreeController *treeNodesController; // @synthesize treeNodesController=_treeNodesController;
@property(nonatomic) __weak NSSearchField *searchField; // @synthesize searchField=_searchField;
@property(nonatomic) __weak NSOutlineView *outlineView; // @synthesize outlineView=_outlineView;
@property(nonatomic) __weak id <SMComponentOutlineControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) SMInterfaceServer *selectedServer; // @synthesize selectedServer=_selectedServer;
- (void).cxx_destruct;
- (void)controlTextDidChange:(id)arg1;
- (void)outlineViewItemDidExpand:(id)arg1;
- (void)outlineViewItemDidCollapse:(id)arg1;
- (void)outlineViewSelectionDidChange:(id)arg1;
- (void)outlineViewSelectionIsChanging:(id)arg1;
- (id)outlineView:(id)arg1 viewForTableColumn:(id)arg2 item:(id)arg3;
- (id)outlineView:(id)arg1 rowViewForItem:(id)arg2;
- (BOOL)validateUserInterfaceItem:(id)arg1;
- (void)filterLayers:(id)arg1;
- (void)filterCells:(id)arg1;
- (void)filterConstraints:(id)arg1;
- (void)doubleClickRow:(id)arg1;
- (void)updateFilterPredicate;
- (void)updateControllerSelection;
- (void)updateSelectedTreeNodes;
- (void)updatedInterface;
- (void)updateRootTreeNodes;
- (void)fitColumn;
@property(readonly, nonatomic, getter=isConnected) BOOL connected;
- (void)viewWillUninstall;
- (void)viewDidInstall;
- (void)loadView;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

