//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <SMFoundation/SMViewController.h>

#import "NSMenuDelegate-Protocol.h"

@class NSImageView, NSPopUpButton, NSString, SMInterface, SMInterfaceTreeNode, SMMagnificationView, SMView;
@protocol SMComponentContentControllerDelegate;

__attribute__((visibility("hidden")))
@interface SMComponentContentController : SMViewController <NSMenuDelegate>
{
    SMInterface *_interface;
    id <SMComponentContentControllerDelegate> _delegate;
    SMInterfaceTreeNode *_selectedTreeNode;
    SMView *_backgroundView;
    SMView *_patternView;
    NSImageView *_contentView;
    SMMagnificationView *_magnificationView;
    NSPopUpButton *_magnificationButton;
}

@property(nonatomic) __weak NSPopUpButton *magnificationButton; // @synthesize magnificationButton=_magnificationButton;
@property(nonatomic) __weak SMMagnificationView *magnificationView; // @synthesize magnificationView=_magnificationView;
@property(nonatomic) __weak NSImageView *contentView; // @synthesize contentView=_contentView;
@property(nonatomic) __weak SMView *patternView; // @synthesize patternView=_patternView;
@property(nonatomic) __weak SMView *backgroundView; // @synthesize backgroundView=_backgroundView;
@property(retain, nonatomic) SMInterfaceTreeNode *selectedTreeNode; // @synthesize selectedTreeNode=_selectedTreeNode;
@property(nonatomic) __weak id <SMComponentContentControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) SMInterface *interface; // @synthesize interface=_interface;
- (void).cxx_destruct;
- (void)menuWillOpen:(id)arg1;
- (void)selectMagnificationFactor:(id)arg1;
- (void)toggleSubviews:(id)arg1;
- (void)selectBackgroundColor:(id)arg1;
- (void)togglePattern:(id)arg1;
- (void)updateMagnificationMenu;
- (void)updatedComponentImage;
- (void)viewWillUninstall;
- (void)viewDidInstall;
- (void)loadView;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

