//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSString, SMEnterLicenseViewController;

@protocol SMEnterLicenseViewControllerDelegate <NSObject>
- (void)enterLicenseViewControllerDidSelectClose:(SMEnterLicenseViewController *)arg1;
- (void)enterLicenseViewControllerDidSelectTrial:(SMEnterLicenseViewController *)arg1;
- (void)enterLicenseViewControllerDidSelectRegister:(SMEnterLicenseViewController *)arg1 withLicenseName:(NSString *)arg2 code:(NSString *)arg3;
@end

