//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <SMFoundation/SMViewController.h>

@class NSImage, NSString;
@protocol SMEnterLicenseViewControllerDelegate;

__attribute__((visibility("hidden")))
@interface SMEnterLicenseViewController : SMViewController
{
    NSImage *_applicationImage;
    NSString *_applicationName;
    NSString *_licenseName;
    NSString *_licenseCode;
    id <SMEnterLicenseViewControllerDelegate> _delegate;
}

+ (id)keyPathsForValuesAffectingRegisterEnabled;
@property(nonatomic) __weak id <SMEnterLicenseViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(copy, nonatomic) NSString *licenseCode; // @synthesize licenseCode=_licenseCode;
@property(copy, nonatomic) NSString *licenseName; // @synthesize licenseName=_licenseName;
@property(copy, nonatomic) NSString *applicationName; // @synthesize applicationName=_applicationName;
@property(retain, nonatomic) NSImage *applicationImage; // @synthesize applicationImage=_applicationImage;
- (void).cxx_destruct;
- (void)close:(id)arg1;
- (void)register:(id)arg1;
- (void)trial:(id)arg1;
@property(readonly, nonatomic, getter=isRegisterEnabled) BOOL registerEnabled;
- (void)viewWillUnload;
- (void)loadView;

@end

