//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSTextFieldCell.h>

@class NSImage;

__attribute__((visibility("hidden")))
@interface SMImageAndTextFieldCell : NSTextFieldCell
{
    NSImage *_sm_image;
}

@property(retain) NSImage *sm_image; // @synthesize sm_image=_sm_image;
- (void).cxx_destruct;
- (struct CGSize)cellSize;
- (void)drawWithFrame:(struct CGRect)arg1 inView:(id)arg2;
- (void)selectWithFrame:(struct CGRect)arg1 inView:(id)arg2 editor:(id)arg3 delegate:(id)arg4 start:(long long)arg5 length:(long long)arg6;
- (void)editWithFrame:(struct CGRect)arg1 inView:(id)arg2 editor:(id)arg3 delegate:(id)arg4 event:(id)arg5;
- (BOOL)isGroupCell;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)init;

@end

