//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <SMFoundation/SMInspectorProperty.h>

@class NSNumber, NSString, NSView, NSViewAnimation, SMAutoresizingSelectionView;

__attribute__((visibility("hidden")))
@interface SMInspectorAutoresizingProperty : SMInspectorProperty
{
    BOOL _updatingValues;
    NSNumber *_flipped;
    NSString *_flippedKeyPath;
    NSView *_superView;
    NSView *_subView;
    SMAutoresizingSelectionView *_autoresizingSelectionView;
    NSViewAnimation *_animation1;
    NSViewAnimation *_animation2;
    NSViewAnimation *_animation3;
    NSViewAnimation *_animation4;
}

+ (id)keyPathsForValuesAffectingInternalEnabled;
@property(retain, nonatomic) NSViewAnimation *animation4; // @synthesize animation4=_animation4;
@property(retain, nonatomic) NSViewAnimation *animation3; // @synthesize animation3=_animation3;
@property(retain, nonatomic) NSViewAnimation *animation2; // @synthesize animation2=_animation2;
@property(retain, nonatomic) NSViewAnimation *animation1; // @synthesize animation1=_animation1;
@property(nonatomic) BOOL updatingValues; // @synthesize updatingValues=_updatingValues;
@property(nonatomic) __weak SMAutoresizingSelectionView *autoresizingSelectionView; // @synthesize autoresizingSelectionView=_autoresizingSelectionView;
@property(nonatomic) __weak NSView *subView; // @synthesize subView=_subView;
@property(nonatomic) __weak NSView *superView; // @synthesize superView=_superView;
@property(copy, nonatomic) NSString *flippedKeyPath; // @synthesize flippedKeyPath=_flippedKeyPath;
@property(retain, nonatomic, getter=isFlipped) NSNumber *flipped; // @synthesize flipped=_flipped;
- (void).cxx_destruct;
- (void)mouseExited:(id)arg1;
- (void)mouseEntered:(id)arg1;
- (BOOL)isAnimationRunning;
- (void)stopAnimation;
- (void)startAnimation;
- (void)updateExampleView;
@property(readonly, nonatomic, getter=isInternalEnabled) BOOL internalEnabled;
- (void)updateFlipped;
- (void)updateReflectedValueWithValue:(id)arg1 mask:(unsigned long long)arg2;
- (void)updateValues;
- (void)viewWillUninstall;
- (void)viewDidInstall;
- (void)loadView;

@end

