//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSKeyedUnarchiverDelegate-Protocol.h"
#import "SMInterfaceComponentDelegate-Protocol.h"
#import "SMServerDelegate-Protocol.h"

@class NSArray, NSMutableDictionary, NSString, SMDelayedInvocation, SMInterface, SMServer;
@protocol SMInterfaceServerDelegate;

__attribute__((visibility("hidden")))
@interface SMInterfaceServer : NSObject <SMServerDelegate, SMInterfaceComponentDelegate, NSKeyedUnarchiverDelegate>
{
    BOOL _selectionMode;
    BOOL _showSubviews;
    BOOL _updatingSelectedComponents;
    BOOL _updatingSelectedMode;
    SMServer *_server;
    id <SMInterfaceServerDelegate> _delegate;
    NSString *_bundleName;
    NSString *_bundleIdentifier;
    NSString *_hostName;
    NSString *_version;
    SMInterface *_interface;
    double _progress;
    NSArray *_types;
    NSString *_name;
    NSMutableDictionary *_interfaceComponentsByIndex;
    NSMutableDictionary *_componentPropertyTransformersForClassName;
    SMDelayedInvocation *_updateTreeNodesInvocation;
}

+ (id)keyPathsForValuesAffectingConnected;
+ (id)keyPathsForValuesAffectingLocal;
+ (id)keyPathsForValuesAffectingDisplayName;
@property(retain, nonatomic) SMDelayedInvocation *updateTreeNodesInvocation; // @synthesize updateTreeNodesInvocation=_updateTreeNodesInvocation;
@property(nonatomic) BOOL updatingSelectedMode; // @synthesize updatingSelectedMode=_updatingSelectedMode;
@property(nonatomic) BOOL updatingSelectedComponents; // @synthesize updatingSelectedComponents=_updatingSelectedComponents;
@property(retain, nonatomic) NSMutableDictionary *componentPropertyTransformersForClassName; // @synthesize componentPropertyTransformersForClassName=_componentPropertyTransformersForClassName;
@property(retain, nonatomic) NSMutableDictionary *interfaceComponentsByIndex; // @synthesize interfaceComponentsByIndex=_interfaceComponentsByIndex;
@property(copy, nonatomic) NSString *name; // @synthesize name=_name;
@property(copy, nonatomic) NSArray *types; // @synthesize types=_types;
@property(nonatomic) BOOL showSubviews; // @synthesize showSubviews=_showSubviews;
@property(nonatomic) double progress; // @synthesize progress=_progress;
@property(nonatomic) BOOL selectionMode; // @synthesize selectionMode=_selectionMode;
@property(retain, nonatomic) SMInterface *interface; // @synthesize interface=_interface;
@property(copy, nonatomic) NSString *version; // @synthesize version=_version;
@property(copy, nonatomic) NSString *hostName; // @synthesize hostName=_hostName;
@property(copy, nonatomic) NSString *bundleIdentifier; // @synthesize bundleIdentifier=_bundleIdentifier;
@property(copy, nonatomic) NSString *bundleName; // @synthesize bundleName=_bundleName;
@property(nonatomic) __weak id <SMInterfaceServerDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) SMServer *server; // @synthesize server=_server;
- (void).cxx_destruct;
- (Class)unarchiver:(id)arg1 cannotDecodeObjectOfClassName:(id)arg2 originalClasses:(id)arg3;
- (void)interfaceComponent:(id)arg1 didChangeValueForKey:(id)arg2 change:(id)arg3;
- (void)didReceiveSelectedComponent:(id)arg1;
- (void)didReceiveComponentImage:(id)arg1;
- (void)didReceiveComponent:(id)arg1;
- (void)didReceiveInfo:(id)arg1;
- (void)server:(id)arg1 didEncounterError:(id)arg2;
- (void)server:(id)arg1 didReceiveObject:(id)arg2;
- (void)serverDidDisconnect:(id)arg1;
- (id)createComponentForIndex:(id)arg1;
- (id)componentFromDictionary:(id)arg1;
- (void)updatedSelectionMode;
- (void)updatedSelectedTreeNodes;
- (void)sendValue:(id)arg1 forKey:(id)arg2 ofComponent:(id)arg3;
- (void)fetchComponentImage:(id)arg1;
- (void)fetchComponent:(id)arg1;
- (void)fetchComponents;
- (void)sendHighlight;
- (void)sendSelection;
- (void)sendSelectionMode;
- (void)fetchSoundResources;
- (void)fetchImageResources;
- (void)sendTypes;
@property(readonly, copy) NSString *description;
- (void)refreshComponent:(id)arg1;
- (void)refresh;
- (void)disconnect;
@property(readonly, nonatomic, getter=isBundleIdentifierValid) BOOL bundleIdentifierValid;
@property(readonly, nonatomic, getter=isVersionValid) BOOL versionValid;
@property(readonly, nonatomic, getter=isConnected) BOOL connected;
@property(readonly, nonatomic, getter=isLocal) BOOL local;
@property(readonly, nonatomic) NSString *displayName;
- (void)loadTypes;
- (void)dealloc;
- (id)initWithServer:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

