//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SMInspectorAdvancedTenFourDateFormatProperty.h"

@class NSArray;

__attribute__((visibility("hidden")))
@interface SMInspectorAdvancedPreTenFourDateFormatProperty : SMInspectorAdvancedTenFourDateFormatProperty
{
    NSArray *_presets;
}

@property(copy, nonatomic) NSArray *presets; // @synthesize presets=_presets;
- (void).cxx_destruct;
- (id)initWithOwner:(id)arg1;

@end

