//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSPredicate, SMInterfaceComponent;

__attribute__((visibility("hidden")))
@interface SMInterfaceTreeNode : NSObject
{
    SMInterfaceComponent *_component;
    NSArray *_childNodes;
    SMInterfaceTreeNode *_parentNode;
    NSPredicate *_filterPredicate;
    NSArray *_filteredNodes;
}

@property(copy, nonatomic) NSArray *filteredNodes; // @synthesize filteredNodes=_filteredNodes;
@property(retain, nonatomic) NSPredicate *filterPredicate; // @synthesize filterPredicate=_filterPredicate;
@property(nonatomic) __weak SMInterfaceTreeNode *parentNode; // @synthesize parentNode=_parentNode;
@property(copy, nonatomic) NSArray *childNodes; // @synthesize childNodes=_childNodes;
@property(retain, nonatomic) SMInterfaceComponent *component; // @synthesize component=_component;
- (void).cxx_destruct;
- (void)updateFilteredNodes;
- (id)description;
- (BOOL)isDescendantOf:(id)arg1;
- (id)treeNodeWithComponent:(id)arg1;
- (id)treeNodeWithInstance:(unsigned long long)arg1;

@end

