//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <SMFoundation/SMInspectorProperty.h>

@class NSNumber, NSString, SMInspectorBooleanProperty, SMInspectorNumberProperty;

__attribute__((visibility("hidden")))
@interface SMInspectorPoint3DProperty : SMInspectorProperty
{
    BOOL _nilValueControlIsOffWhenNil;
    BOOL _updatingValues;
    NSString *_xTitle;
    NSString *_xTitleKeyPath;
    NSString *_yTitle;
    NSString *_yTitleKeyPath;
    NSString *_zTitle;
    NSString *_zTitleKeyPath;
    NSNumber *_increment;
    NSString *_incrementKeyPath;
    NSNumber *_maximumX;
    NSString *_maximumXKeyPath;
    NSNumber *_minimumX;
    NSString *_minimumXKeyPath;
    NSNumber *_maximumY;
    NSString *_maximumYKeyPath;
    NSNumber *_minimumY;
    NSString *_minimumYKeyPath;
    NSNumber *_maximumZ;
    NSString *_maximumZKeyPath;
    NSNumber *_minimumZ;
    NSString *_minimumZKeyPath;
    unsigned long long _formatStyle;
    NSString *_formatUnit;
    unsigned long long _style;
    NSString *_nonNilValueKeyPath;
    SMInspectorNumberProperty *_xProperty;
    SMInspectorNumberProperty *_yProperty;
    SMInspectorNumberProperty *_zProperty;
    SMInspectorBooleanProperty *_nonNilProperty;
    id _x;
    id _y;
    id _z;
    id _nonNil;
}

@property(nonatomic) BOOL updatingValues; // @synthesize updatingValues=_updatingValues;
@property(retain, nonatomic) id nonNil; // @synthesize nonNil=_nonNil;
@property(retain, nonatomic) id z; // @synthesize z=_z;
@property(retain, nonatomic) id y; // @synthesize y=_y;
@property(retain, nonatomic) id x; // @synthesize x=_x;
@property(retain, nonatomic) SMInspectorBooleanProperty *nonNilProperty; // @synthesize nonNilProperty=_nonNilProperty;
@property(retain, nonatomic) SMInspectorNumberProperty *zProperty; // @synthesize zProperty=_zProperty;
@property(retain, nonatomic) SMInspectorNumberProperty *yProperty; // @synthesize yProperty=_yProperty;
@property(retain, nonatomic) SMInspectorNumberProperty *xProperty; // @synthesize xProperty=_xProperty;
@property(copy, nonatomic) NSString *nonNilValueKeyPath; // @synthesize nonNilValueKeyPath=_nonNilValueKeyPath;
@property(nonatomic) BOOL nilValueControlIsOffWhenNil; // @synthesize nilValueControlIsOffWhenNil=_nilValueControlIsOffWhenNil;
@property(nonatomic) unsigned long long style; // @synthesize style=_style;
@property(copy, nonatomic) NSString *formatUnit; // @synthesize formatUnit=_formatUnit;
@property(nonatomic) unsigned long long formatStyle; // @synthesize formatStyle=_formatStyle;
@property(copy, nonatomic) NSString *minimumZKeyPath; // @synthesize minimumZKeyPath=_minimumZKeyPath;
@property(retain, nonatomic) NSNumber *minimumZ; // @synthesize minimumZ=_minimumZ;
@property(copy, nonatomic) NSString *maximumZKeyPath; // @synthesize maximumZKeyPath=_maximumZKeyPath;
@property(retain, nonatomic) NSNumber *maximumZ; // @synthesize maximumZ=_maximumZ;
@property(copy, nonatomic) NSString *minimumYKeyPath; // @synthesize minimumYKeyPath=_minimumYKeyPath;
@property(retain, nonatomic) NSNumber *minimumY; // @synthesize minimumY=_minimumY;
@property(copy, nonatomic) NSString *maximumYKeyPath; // @synthesize maximumYKeyPath=_maximumYKeyPath;
@property(retain, nonatomic) NSNumber *maximumY; // @synthesize maximumY=_maximumY;
@property(copy, nonatomic) NSString *minimumXKeyPath; // @synthesize minimumXKeyPath=_minimumXKeyPath;
@property(retain, nonatomic) NSNumber *minimumX; // @synthesize minimumX=_minimumX;
@property(copy, nonatomic) NSString *maximumXKeyPath; // @synthesize maximumXKeyPath=_maximumXKeyPath;
@property(retain, nonatomic) NSNumber *maximumX; // @synthesize maximumX=_maximumX;
@property(copy, nonatomic) NSString *incrementKeyPath; // @synthesize incrementKeyPath=_incrementKeyPath;
@property(retain, nonatomic) NSNumber *increment; // @synthesize increment=_increment;
@property(copy, nonatomic) NSString *zTitleKeyPath; // @synthesize zTitleKeyPath=_zTitleKeyPath;
@property(copy, nonatomic) NSString *zTitle; // @synthesize zTitle=_zTitle;
@property(copy, nonatomic) NSString *yTitleKeyPath; // @synthesize yTitleKeyPath=_yTitleKeyPath;
@property(copy, nonatomic) NSString *yTitle; // @synthesize yTitle=_yTitle;
@property(copy, nonatomic) NSString *xTitleKeyPath; // @synthesize xTitleKeyPath=_xTitleKeyPath;
@property(copy, nonatomic) NSString *xTitle; // @synthesize xTitle=_xTitle;
- (void).cxx_destruct;
- (void)toggleNilValue;
- (void)updateZ;
- (void)updateY;
- (void)updateX;
- (void)updateValues;
- (id)viewForBaselineAlignment;
- (void)viewWillUninstall;
- (void)viewDidInstall;
- (void)viewWillUnload;
- (void)loadView;
- (id)initWithOwner:(id)arg1;

@end

