//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <SMFoundation/SMViewController.h>

#import "NSOutlineViewDataSource-Protocol.h"
#import "NSOutlineViewDelegate-Protocol.h"
#import "NSTableViewDelegate-Protocol.h"
#import "NSTextFieldDelegate-Protocol.h"

@class NSArray, NSMenu, NSMenuItem, NSPopUpButton, NSString, SMActionBar, SMConnectedView, SMInterfaceServer, SMService;
@protocol SMInterfaceConnectionControllerDelegate;

__attribute__((visibility("hidden")))
@interface SMInterfaceConnectionController : SMViewController <NSOutlineViewDataSource, NSOutlineViewDelegate, NSTableViewDelegate, NSTextFieldDelegate>
{
    BOOL _allowRemoteConnections;
    BOOL _updatingSelectedServer;
    SMService *_service;
    NSArray *_servers;
    SMInterfaceServer *_selectedServer;
    id <SMInterfaceConnectionControllerDelegate> _delegate;
    SMActionBar *_connectionBar;
    NSPopUpButton *_serversPopUpButton;
    NSMenu *_serversMenu;
    NSMenuItem *_noTargetMenuItem;
    SMConnectedView *_connectedView;
}

@property(nonatomic) BOOL updatingSelectedServer; // @synthesize updatingSelectedServer=_updatingSelectedServer;
@property(nonatomic) __weak SMConnectedView *connectedView; // @synthesize connectedView=_connectedView;
@property(retain, nonatomic) NSMenuItem *noTargetMenuItem; // @synthesize noTargetMenuItem=_noTargetMenuItem;
@property(nonatomic) __weak NSMenu *serversMenu; // @synthesize serversMenu=_serversMenu;
@property(nonatomic) __weak NSPopUpButton *serversPopUpButton; // @synthesize serversPopUpButton=_serversPopUpButton;
@property(nonatomic) __weak SMActionBar *connectionBar; // @synthesize connectionBar=_connectionBar;
@property(nonatomic) __weak id <SMInterfaceConnectionControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) SMInterfaceServer *selectedServer; // @synthesize selectedServer=_selectedServer;
@property(copy, nonatomic) NSArray *servers; // @synthesize servers=_servers;
@property(nonatomic) BOOL allowRemoteConnections; // @synthesize allowRemoteConnections=_allowRemoteConnections;
@property(retain, nonatomic) SMService *service; // @synthesize service=_service;
- (void).cxx_destruct;
- (void)selectTarget:(id)arg1;
- (void)updateServersMenu;
- (void)updatedSelectedServer;
- (void)viewWillUninstall;
- (void)viewDidInstall;
- (void)loadView;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

