//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSPredicate, NSString, SMInterfaceTreeNode;

__attribute__((visibility("hidden")))
@interface SMInterface : NSObject
{
    BOOL _local;
    NSString *_bundleName;
    NSString *_bundleIdentifier;
    NSString *_version;
    NSString *_displayName;
    double _displayScale;
    NSArray *_components;
    NSArray *_imageResources;
    NSArray *_soundResources;
    NSArray *_treeNodes;
    NSArray *_selectedTreeNodes;
    SMInterfaceTreeNode *_highlightedTreeNode;
    NSPredicate *_filterPredicate;
    NSArray *_filteredTreeNodes;
}

@property(copy, nonatomic) NSArray *filteredTreeNodes; // @synthesize filteredTreeNodes=_filteredTreeNodes;
@property(retain, nonatomic) NSPredicate *filterPredicate; // @synthesize filterPredicate=_filterPredicate;
@property(retain, nonatomic) SMInterfaceTreeNode *highlightedTreeNode; // @synthesize highlightedTreeNode=_highlightedTreeNode;
@property(copy, nonatomic) NSArray *selectedTreeNodes; // @synthesize selectedTreeNodes=_selectedTreeNodes;
@property(copy, nonatomic) NSArray *treeNodes; // @synthesize treeNodes=_treeNodes;
@property(copy, nonatomic) NSArray *soundResources; // @synthesize soundResources=_soundResources;
@property(copy, nonatomic) NSArray *imageResources; // @synthesize imageResources=_imageResources;
@property(copy, nonatomic) NSArray *components; // @synthesize components=_components;
@property(nonatomic, getter=isLocal) BOOL local; // @synthesize local=_local;
@property(nonatomic) double displayScale; // @synthesize displayScale=_displayScale;
@property(copy, nonatomic) NSString *displayName; // @synthesize displayName=_displayName;
@property(copy, nonatomic) NSString *version; // @synthesize version=_version;
@property(copy, nonatomic) NSString *bundleIdentifier; // @synthesize bundleIdentifier=_bundleIdentifier;
@property(copy, nonatomic) NSString *bundleName; // @synthesize bundleName=_bundleName;
- (void).cxx_destruct;
- (void)updateFilteredNodes;
- (void)updateTreeNode:(id)arg1 withComponent:(id)arg2 componentStack:(id)arg3;
- (void)updateTreeNodes;
- (id)treeNodeWithComponent:(id)arg1;
- (id)treeNodeWithInstance:(unsigned long long)arg1;
- (id)init;

@end

