//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <SMFoundation/SMInspectorProperty.h>

#import "NSControlTextEditingDelegate-Protocol.h"
#import "NSTokenFieldDelegate-Protocol.h"

@class NSArray, NSDate, NSMenu, NSRegularExpression, NSString, NSTokenField, SMDelayedInvocation;

__attribute__((visibility("hidden")))
@interface SMInspectorBasicTenFourDateFormatProperty : SMInspectorProperty <NSTokenFieldDelegate, NSControlTextEditingDelegate>
{
    NSString *_placeholder;
    NSDate *_date;
    NSRegularExpression *_expression;
    NSArray *_tokens;
    NSTokenField *_tokenField;
    SMDelayedInvocation *_updateViewInvocation;
}

@property(retain, nonatomic) SMDelayedInvocation *updateViewInvocation; // @synthesize updateViewInvocation=_updateViewInvocation;
@property(nonatomic) __weak NSTokenField *tokenField; // @synthesize tokenField=_tokenField;
@property(copy, nonatomic) NSArray *tokens; // @synthesize tokens=_tokens;
@property(retain, nonatomic) NSRegularExpression *expression; // @synthesize expression=_expression;
@property(copy, nonatomic) NSDate *date; // @synthesize date=_date;
@property(copy, nonatomic) NSString *placeholder; // @synthesize placeholder=_placeholder;
- (void).cxx_destruct;
- (id)displayStringForSymbol:(id)arg1;
- (unsigned long long)symbolTypeForSymbol:(id)arg1;
- (id)tokensForString:(id)arg1;
- (id)dateFormatFromTokens:(id)arg1;
- (void)updateTokens;
- (void)tokenPopupSelected:(id)arg1;
- (void)controlTextDidChange:(id)arg1;
- (id)tokenField:(id)arg1 readFromPasteboard:(id)arg2;
- (BOOL)tokenField:(id)arg1 writeRepresentedObjects:(id)arg2 toPasteboard:(id)arg3;
- (id)tokenField:(id)arg1 menuForRepresentedObject:(id)arg2;
- (BOOL)tokenField:(id)arg1 hasMenuForRepresentedObject:(id)arg2;
- (id)tokenField:(id)arg1 displayStringForRepresentedObject:(id)arg2;
- (id)tokenField:(id)arg1 representedObjectForEditingString:(id)arg2;
- (id)tokenField:(id)arg1 editingStringForRepresentedObject:(id)arg2;
- (unsigned long long)tokenField:(id)arg1 styleForRepresentedObject:(id)arg2;
- (void)controlTextDidEndEditing:(id)arg1;
- (void)userDidChangeValue:(id)arg1;
- (void)updateView;
- (id)viewForBaselineAlignment;
- (void)viewWillUninstall;
- (void)viewDidInstall;
- (void)loadView;
- (id)initWithOwner:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(retain, nonatomic) NSMenu *menu;
@property(readonly) Class superclass;

@end

