//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <SMFoundation/SMInspectorProperty.h>

@class NSArray, NSMutableDictionary, NSNumber, NSString, SMDelayedInvocation, SMInspectorSection;

__attribute__((visibility("hidden")))
@interface SMInspectorPrioritiesListProperty : SMInspectorProperty
{
    BOOL _updatingValues;
    NSString *_propertyTitles;
    NSNumber *_increment;
    NSString *_incrementKeyPath;
    NSNumber *_maximum;
    NSString *_maximumKeyPath;
    NSNumber *_minimum;
    NSString *_minimumKeyPath;
    SMInspectorSection *_section;
    NSArray *_valueSlivers;
    NSArray *_valueProperties;
    NSMutableDictionary *_valuesDictionary;
    SMDelayedInvocation *_updateViewInvocation;
}

@property(nonatomic) BOOL updatingValues; // @synthesize updatingValues=_updatingValues;
@property(retain, nonatomic) SMDelayedInvocation *updateViewInvocation; // @synthesize updateViewInvocation=_updateViewInvocation;
@property(retain, nonatomic) NSMutableDictionary *valuesDictionary; // @synthesize valuesDictionary=_valuesDictionary;
@property(copy, nonatomic) NSArray *valueProperties; // @synthesize valueProperties=_valueProperties;
@property(copy, nonatomic) NSArray *valueSlivers; // @synthesize valueSlivers=_valueSlivers;
@property(retain, nonatomic) SMInspectorSection *section; // @synthesize section=_section;
@property(copy, nonatomic) NSString *minimumKeyPath; // @synthesize minimumKeyPath=_minimumKeyPath;
@property(retain, nonatomic) NSNumber *minimum; // @synthesize minimum=_minimum;
@property(copy, nonatomic) NSString *maximumKeyPath; // @synthesize maximumKeyPath=_maximumKeyPath;
@property(retain, nonatomic) NSNumber *maximum; // @synthesize maximum=_maximum;
@property(copy, nonatomic) NSString *incrementKeyPath; // @synthesize incrementKeyPath=_incrementKeyPath;
@property(retain, nonatomic) NSNumber *increment; // @synthesize increment=_increment;
@property(copy, nonatomic) NSString *propertyTitles; // @synthesize propertyTitles=_propertyTitles;
- (void).cxx_destruct;
- (void)userDidChangeValue:(id)arg1;
- (void)updateView;
- (id)viewForBaselineAlignment;
- (void)viewWillUninstall;
- (void)viewDidInstall;
- (void)loadView;
- (id)initWithOwner:(id)arg1;

@end

