//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSWindowController.h>

@class NSNumber;
@protocol SMJumpToInstanceSheetControllerDelegate;

__attribute__((visibility("hidden")))
@interface SMJumpToInstanceSheetController : NSWindowController
{
    id <SMJumpToInstanceSheetControllerDelegate> _delegate;
    NSNumber *_instance;
}

@property(retain, nonatomic) NSNumber *instance; // @synthesize instance=_instance;
@property(nonatomic) __weak id <SMJumpToInstanceSheetControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)confirm:(id)arg1;
- (void)cancel:(id)arg1;
- (void)windowDidLoad;
- (id)windowNibName;

@end

