//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDate, NSString;

__attribute__((visibility("hidden")))
@interface SMLicenseManager : NSObject
{
    BOOL _licensed;
    BOOL _expired;
    NSString *_licenseName;
    NSString *_licenseCode;
    unsigned long long _daysUntilExpiration;
    NSDate *_firstLaunchDate;
}

+ (BOOL)verifyLicenseWithName:(id)arg1 code:(id)arg2;
+ (void)load;
+ (id)sharedInstance;
@property(copy, nonatomic) NSDate *firstLaunchDate; // @synthesize firstLaunchDate=_firstLaunchDate;
@property(nonatomic, getter=isExpired) BOOL expired; // @synthesize expired=_expired;
@property(nonatomic) unsigned long long daysUntilExpiration; // @synthesize daysUntilExpiration=_daysUntilExpiration;
@property(nonatomic, getter=isLicensed) BOOL licensed; // @synthesize licensed=_licensed;
@property(copy, nonatomic) NSString *licenseCode; // @synthesize licenseCode=_licenseCode;
@property(copy, nonatomic) NSString *licenseName; // @synthesize licenseName=_licenseName;
- (void).cxx_destruct;
- (void)writeSettings;
- (id)settingsURL;
- (BOOL)registerLicenseWithName:(id)arg1 code:(id)arg2;
- (id)init;

@end

