//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSWindowController.h>

#import "NSWindowDelegate-Protocol.h"
#import "SMEnterLicenseViewControllerDelegate-Protocol.h"
#import "SMInvalidLicenseViewControllerDelegate-Protocol.h"
#import "SMValidLicenseViewControllerDelegate-Protocol.h"

@class NSString, SMContainerView, SMEnterLicenseViewController, SMInvalidLicenseViewController, SMValidLicenseViewController;
@protocol SMLicenseWindowControllerDelegate;

__attribute__((visibility("hidden")))
@interface SMLicenseWindowController : NSWindowController <NSWindowDelegate, SMEnterLicenseViewControllerDelegate, SMInvalidLicenseViewControllerDelegate, SMValidLicenseViewControllerDelegate>
{
    BOOL _performingClose;
    id <SMLicenseWindowControllerDelegate> _delegate;
    SMContainerView *_containerView;
    SMEnterLicenseViewController *_viewController1;
    SMInvalidLicenseViewController *_viewController2;
    SMValidLicenseViewController *_viewController3;
}

@property(nonatomic) BOOL performingClose; // @synthesize performingClose=_performingClose;
@property(retain, nonatomic) SMValidLicenseViewController *viewController3; // @synthesize viewController3=_viewController3;
@property(retain, nonatomic) SMInvalidLicenseViewController *viewController2; // @synthesize viewController2=_viewController2;
@property(retain, nonatomic) SMEnterLicenseViewController *viewController1; // @synthesize viewController1=_viewController1;
@property(nonatomic) __weak SMContainerView *containerView; // @synthesize containerView=_containerView;
@property(nonatomic) __weak id <SMLicenseWindowControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)validLicenseViewControllerDidSelectClose:(id)arg1;
- (void)validLicenseViewControllerDidSelectChangeLicense:(id)arg1;
- (void)invalidLicenseViewControllerDidSelectClose:(id)arg1;
- (void)invalidLicenseViewControllerDidSelectBack:(id)arg1;
- (void)enterLicenseViewControllerDidSelectClose:(id)arg1;
- (void)enterLicenseViewControllerDidSelectTrial:(id)arg1;
- (void)enterLicenseViewControllerDidSelectRegister:(id)arg1 withLicenseName:(id)arg2 code:(id)arg3;
- (void)cancelOperation:(id)arg1;
- (void)windowWillClose:(id)arg1;
- (BOOL)windowShouldClose:(id)arg1;
- (void)loadView:(unsigned long long)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

