//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSWindowController.h>

#import "SMAttachWindowControllerDelegate-Protocol.h"
#import "SMComponentContentControllerDelegate-Protocol.h"
#import "SMComponentOutlineControllerDelegate-Protocol.h"
#import "SMComponentPathControllerDelegate-Protocol.h"
#import "SMInterfaceConnectionControllerDelegate-Protocol.h"
#import "SMInterfaceServerDelegate-Protocol.h"
#import "SMJumpToInstanceSheetControllerDelegate-Protocol.h"
#import "SMServiceDelegate-Protocol.h"

@class NSArray, NSButton, NSString, NSTimer, NSToolbarItem, NSUndoManager, SMAttachWindowController, SMAuthorizedInjector, SMComponentContentController, SMComponentOutlineController, SMComponentPathController, SMComponentsInspector, SMContainerView, SMDelayedInvocation, SMInterfaceConnectionController, SMInterfaceServer, SMJumpToInstanceSheetController, SMPrioritySplitViewDelegate, SMService, SMSplitView, SMWaitingWindowController;

__attribute__((visibility("hidden")))
@interface SMMainWindowController : NSWindowController <SMAttachWindowControllerDelegate, SMServiceDelegate, SMInterfaceConnectionControllerDelegate, SMComponentPathControllerDelegate, SMComponentOutlineControllerDelegate, SMComponentContentControllerDelegate, SMInterfaceServerDelegate, SMJumpToInstanceSheetControllerDelegate>
{
    BOOL _alwaysOnTop;
    BOOL _allowRemoteConnections;
    BOOL _automaticallyRefresh;
    SMWaitingWindowController *_waitingWindowController;
    SMAttachWindowController *_attachWindowController;
    NSButton *_alwaysOnTopButton;
    NSToolbarItem *_interfaceConnectionToolbarItem;
    SMContainerView *_connectionContainerView;
    SMInterfaceConnectionController *_interfaceConnectionController;
    NSToolbarItem *_componentPathToolbarItem;
    SMContainerView *_pathContainerView;
    SMComponentPathController *_componentPathController;
    SMContainerView *_outlineContainerView;
    SMComponentOutlineController *_componentOutlineController;
    SMContainerView *_contentContainerView;
    SMComponentContentController *_componentContentController;
    SMContainerView *_inspectorContainerView;
    SMComponentsInspector *_componentsInspector;
    SMSplitView *_splitView;
    SMPrioritySplitViewDelegate *_splitViewDelegate;
    SMAuthorizedInjector *_injector;
    SMService *_service;
    NSArray *_servers;
    NSArray *_readyServers;
    SMInterfaceServer *_selectedServer;
    NSTimer *_refreshTimer;
    NSUndoManager *_undoManager;
    SMJumpToInstanceSheetController *_jumpToInstanceSheetController;
    SMDelayedInvocation *_delayedAttachInvocation;
}

+ (id)keyPathsForValuesAffectingWindowTitle;
@property(retain, nonatomic) SMDelayedInvocation *delayedAttachInvocation; // @synthesize delayedAttachInvocation=_delayedAttachInvocation;
@property(retain, nonatomic) SMJumpToInstanceSheetController *jumpToInstanceSheetController; // @synthesize jumpToInstanceSheetController=_jumpToInstanceSheetController;
@property(retain, nonatomic) NSUndoManager *undoManager; // @synthesize undoManager=_undoManager;
@property(retain, nonatomic) NSTimer *refreshTimer; // @synthesize refreshTimer=_refreshTimer;
@property(nonatomic) BOOL automaticallyRefresh; // @synthesize automaticallyRefresh=_automaticallyRefresh;
@property(retain, nonatomic) SMInterfaceServer *selectedServer; // @synthesize selectedServer=_selectedServer;
@property(copy, nonatomic) NSArray *readyServers; // @synthesize readyServers=_readyServers;
@property(copy, nonatomic) NSArray *servers; // @synthesize servers=_servers;
@property(retain, nonatomic) SMService *service; // @synthesize service=_service;
@property(nonatomic) BOOL allowRemoteConnections; // @synthesize allowRemoteConnections=_allowRemoteConnections;
@property(retain, nonatomic) SMAuthorizedInjector *injector; // @synthesize injector=_injector;
@property(retain, nonatomic) SMPrioritySplitViewDelegate *splitViewDelegate; // @synthesize splitViewDelegate=_splitViewDelegate;
@property(nonatomic) __weak SMSplitView *splitView; // @synthesize splitView=_splitView;
@property(retain, nonatomic) SMComponentsInspector *componentsInspector; // @synthesize componentsInspector=_componentsInspector;
@property(nonatomic) __weak SMContainerView *inspectorContainerView; // @synthesize inspectorContainerView=_inspectorContainerView;
@property(retain, nonatomic) SMComponentContentController *componentContentController; // @synthesize componentContentController=_componentContentController;
@property(nonatomic) __weak SMContainerView *contentContainerView; // @synthesize contentContainerView=_contentContainerView;
@property(retain, nonatomic) SMComponentOutlineController *componentOutlineController; // @synthesize componentOutlineController=_componentOutlineController;
@property(nonatomic) __weak SMContainerView *outlineContainerView; // @synthesize outlineContainerView=_outlineContainerView;
@property(retain, nonatomic) SMComponentPathController *componentPathController; // @synthesize componentPathController=_componentPathController;
@property(retain, nonatomic) SMContainerView *pathContainerView; // @synthesize pathContainerView=_pathContainerView;
@property(retain, nonatomic) NSToolbarItem *componentPathToolbarItem; // @synthesize componentPathToolbarItem=_componentPathToolbarItem;
@property(retain, nonatomic) SMInterfaceConnectionController *interfaceConnectionController; // @synthesize interfaceConnectionController=_interfaceConnectionController;
@property(retain, nonatomic) SMContainerView *connectionContainerView; // @synthesize connectionContainerView=_connectionContainerView;
@property(retain, nonatomic) NSToolbarItem *interfaceConnectionToolbarItem; // @synthesize interfaceConnectionToolbarItem=_interfaceConnectionToolbarItem;
@property(nonatomic) BOOL alwaysOnTop; // @synthesize alwaysOnTop=_alwaysOnTop;
@property(retain, nonatomic) NSButton *alwaysOnTopButton; // @synthesize alwaysOnTopButton=_alwaysOnTopButton;
@property(retain, nonatomic) SMAttachWindowController *attachWindowController; // @synthesize attachWindowController=_attachWindowController;
@property(retain, nonatomic) SMWaitingWindowController *waitingWindowController; // @synthesize waitingWindowController=_waitingWindowController;
- (void).cxx_destruct;
- (void)jumpToInstanceSheetController:(id)arg1 didJumpToInstance:(unsigned long long)arg2;
- (void)componentContentController:(id)arg1 didChangeShowSubviews:(BOOL)arg2;
- (void)componentOutlineController:(id)arg1 didSelectTreeNodes:(id)arg2;
- (void)componentPathController:(id)arg1 didChangeSelectionMode:(BOOL)arg2;
- (void)componentPathController:(id)arg1 didSelectTreeNode:(id)arg2;
- (void)interfaceConnectionController:(id)arg1 didSelectServer:(id)arg2;
- (void)interfaceServer:(id)arg1 didChangeValueForKey:(id)arg2 change:(id)arg3 component:(id)arg4;
- (void)interfaceServer:(id)arg1 didReceiveSelectedComponent:(id)arg2;
- (void)interfaceServerDidRefreshInterface:(id)arg1;
- (void)interfaceServerDidGetInfo:(id)arg1;
- (void)interfaceServer:(id)arg1 didEncounterError:(id)arg2;
- (void)interfaceServerDidDisconnect:(id)arg1;
- (id)interfaceServerForServer:(id)arg1;
- (void)service:(id)arg1 didConnectServer:(id)arg2;
- (void)attachWindowControllerDidSelectCancel:(id)arg1;
- (void)attachWindowController:(id)arg1 didSelectApplication:(id)arg2;
- (BOOL)validateUserInterfaceItem:(id)arg1;
- (void)jumpToInstance:(id)arg1;
- (void)saveSnapshot:(id)arg1;
- (void)hideComponents:(id)arg1;
- (void)selectComponent:(id)arg1;
- (void)showSizeInspector:(id)arg1;
- (void)showAttributesInspector:(id)arg1;
- (void)showIdentityInspector:(id)arg1;
- (void)toggleAutomaticRefresh:(id)arg1;
- (void)refresh:(id)arg1;
- (void)toggleAllowRemoteConnections:(id)arg1;
- (void)alwaysOnTop:(id)arg1;
- (void)selectAttach:(id)arg1;
- (void)saveFramework:(id)arg1;
- (void)stopRefreshTimer;
- (void)scheduleRefresh;
- (void)updatedSelectedServerWithOldServer:(id)arg1 newServer:(id)arg2;
- (void)attachToApplication:(id)arg1 selectionMode:(BOOL)arg2;
- (BOOL)installFrameworkToURL:(id)arg1 error:(id *)arg2;
- (id)frameworkSourceURL;
@property(readonly, copy, nonatomic) NSString *windowTitle;
- (BOOL)connectToApplication:(id)arg1 selectionMode:(BOOL)arg2;
- (void)showWindow:(id)arg1;
- (void)windowDidExitFullScreen:(id)arg1;
- (void)windowWillEnterFullScreen:(id)arg1;
- (id)windowWillReturnUndoManager:(id)arg1;
- (void)windowDidLoad;
- (id)windowNibName;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

