//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSPathComponentCell.h>

@class NSTextFieldCell;

__attribute__((visibility("hidden")))
@interface SMPathComponentCell : NSPathComponentCell
{
    NSTextFieldCell *_textFieldCell;
}

@property(retain, nonatomic) NSTextFieldCell *textFieldCell; // @synthesize textFieldCell=_textFieldCell;
- (void).cxx_destruct;
- (void)drawInteriorWithFrame:(struct CGRect)arg1 inView:(id)arg2;

@end

