//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSPathCell.h>

@class NSPathComponentCell, NSTimer;

__attribute__((visibility("hidden")))
@interface SMPathCell : NSPathCell
{
    BOOL _menuWasShown;
    NSPathComponentCell *_clickedPathComponentCell;
    NSTimer *_menuTimer;
}

+ (BOOL)prefersTrackingUntilMouseUp;
@property(nonatomic) BOOL menuWasShown; // @synthesize menuWasShown=_menuWasShown;
@property(retain, nonatomic) NSTimer *menuTimer; // @synthesize menuTimer=_menuTimer;
@property(retain, nonatomic) NSPathComponentCell *clickedPathComponentCell; // @synthesize clickedPathComponentCell=_clickedPathComponentCell;
- (void).cxx_destruct;
- (void)showMenu;
- (BOOL)trackMouse:(id)arg1 inRect:(struct CGRect)arg2 ofView:(id)arg3 untilMouseUp:(BOOL)arg4;

@end

