//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class GCDAsyncSocket, NSString;
@protocol OS_dispatch_queue, SMServerDelegate;

__attribute__((visibility("hidden")))
@interface SMServer : NSObject
{
    BOOL _connected;
    NSString *_host;
    unsigned long long _port;
    id <SMServerDelegate> _delegate;
    GCDAsyncSocket *_socket;
    NSObject<OS_dispatch_queue> *_sendQueue;
    NSObject<OS_dispatch_queue> *_receiveQueue;
}

@property(retain, nonatomic) NSObject<OS_dispatch_queue> *receiveQueue; // @synthesize receiveQueue=_receiveQueue;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *sendQueue; // @synthesize sendQueue=_sendQueue;
@property(retain, nonatomic) GCDAsyncSocket *socket; // @synthesize socket=_socket;
@property(nonatomic) id <SMServerDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic, getter=isConnected) BOOL connected; // @synthesize connected=_connected;
@property(nonatomic) unsigned long long port; // @synthesize port=_port;
@property(copy, nonatomic) NSString *host; // @synthesize host=_host;
- (void).cxx_destruct;
- (void)socket:(id)arg1 didReadData:(id)arg2 withTag:(long long)arg3;
- (void)socketDidDisconnect:(id)arg1 withError:(id)arg2;
- (id)description;
- (void)sendObject:(id)arg1;
- (void)disconnect;
@property(readonly, nonatomic, getter=isLocal) BOOL local;
- (void)dealloc;
- (id)initWithSocket:(id)arg1;

@end

