//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSError, SMServer;
@protocol NSCoding;

@protocol SMServerDelegate <NSObject>
- (void)serverDidDisconnect:(SMServer *)arg1;
- (void)server:(SMServer *)arg1 didEncounterError:(NSError *)arg2;
- (void)server:(SMServer *)arg1 didReceiveObject:(id <NSCoding>)arg2;
@end

