//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSArray, NSError, NSInvocation, NSString, SUAppcast, SUAppcastItem, SUUpdater;
@protocol SUVersionComparison, SUVersionDisplay;

@protocol SUUpdaterDelegate <NSObject>

@optional
- (void)updater:(SUUpdater *)arg1 didAbortWithError:(NSError *)arg2;
- (void)updater:(SUUpdater *)arg1 didCancelInstallUpdateOnQuit:(SUAppcastItem *)arg2;
- (void)updater:(SUUpdater *)arg1 willInstallUpdateOnQuit:(SUAppcastItem *)arg2 immediateInstallationInvocation:(NSInvocation *)arg3;
- (void)updaterDidShowModalAlert:(SUUpdater *)arg1;
- (void)updaterWillShowModalAlert:(SUUpdater *)arg1;
- (NSString *)pathToRelaunchForUpdater:(SUUpdater *)arg1;
- (id <SUVersionDisplay>)versionDisplayerForUpdater:(SUUpdater *)arg1;
- (id <SUVersionComparison>)versionComparatorForUpdater:(SUUpdater *)arg1;
- (void)updaterWillRelaunchApplication:(SUUpdater *)arg1;
- (BOOL)updaterShouldRelaunchApplication:(SUUpdater *)arg1;
- (BOOL)updater:(SUUpdater *)arg1 shouldPostponeRelaunchForUpdate:(SUAppcastItem *)arg2 untilInvoking:(NSInvocation *)arg3;
- (void)updater:(SUUpdater *)arg1 willInstallUpdate:(SUAppcastItem *)arg2;
- (void)updaterDidNotFindUpdate:(SUUpdater *)arg1;
- (void)updater:(SUUpdater *)arg1 didFindValidUpdate:(SUAppcastItem *)arg2;
- (SUAppcastItem *)bestValidUpdateInAppcast:(SUAppcast *)arg1 forUpdater:(SUUpdater *)arg2;
- (void)updater:(SUUpdater *)arg1 didFinishLoadingAppcast:(SUAppcast *)arg2;
- (BOOL)updaterShouldPromptForPermissionToCheckForUpdates:(SUUpdater *)arg1;
- (NSString *)feedURLStringForUpdater:(SUUpdater *)arg1;
- (NSArray *)feedParametersForUpdater:(SUUpdater *)arg1 sendingSystemProfile:(BOOL)arg2;
- (BOOL)updaterMayCheckForUpdates:(SUUpdater *)arg1;
@end

